2021-03-24 08:53:02.020698 (MainThread): Running with dbt=0.18.1
2021-03-24 08:53:02.281632 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.rpc.server.RPCServerTask'>, debug=False, defer=None, exclude=None, host='0.0.0.0', log_cache_events=False, log_format='default', models=None, partial_parse=True, port=8580, profile='user', profiles_dir='/usr/src/develop/.dbt', project_dir=None, record_timing_info=None, rpc_method=None, single_threaded=False, state=None, strict=False, target=None, test_new_parser=False, threads=None, use_cache=True, use_colors=None, vars='{}', version_check=True, warn_error=False, which='rpc', write_json=True)
2021-03-24 08:53:02.308730 (MainThread): Tracking: tracking
2021-03-24 08:53:02.308984 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b4fd9fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44c300a040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b4fddbe0>]}
2021-03-24 08:53:02.309404 (MainThread): Serving RPC server at 0.0.0.0:8580, pid=16
2021-03-24 08:53:02.310013 (MainThread): Supported methods: ['cli_args', 'compile', 'compile_sql', 'deps', 'docs.generate', 'gc', 'get-manifest', 'kill', 'poll', 'ps', 'run', 'run-operation', 'run_sql', 'seed', 'snapshot', 'snapshot-freshness', 'status', 'test']
2021-03-24 08:53:02.310452 (MainThread): Send requests to http://localhost:8580/jsonrpc
2021-03-24 08:53:02.315944 (Thread-1): Parsing macros/adapters.sql
2021-03-24 08:53:02.345514 (Thread-1): Parsing macros/catalog.sql
2021-03-24 08:53:02.347544 (Thread-1): Parsing macros/materializations/table.sql
2021-03-24 08:53:02.351356 (Thread-1): Parsing macros/materializations/merge.sql
2021-03-24 08:53:02.353278 (Thread-1): Parsing macros/materializations/incremental.sql
2021-03-24 08:53:02.362369 (Thread-1): Parsing macros/materializations/view.sql
2021-03-24 08:53:02.364579 (Thread-1): Parsing macros/core.sql
2021-03-24 08:53:02.368176 (Thread-1): Parsing macros/materializations/helpers.sql
2021-03-24 08:53:02.376989 (Thread-1): Parsing macros/materializations/common/merge.sql
2021-03-24 08:53:02.390772 (Thread-1): Parsing macros/materializations/snapshot/snapshot_merge.sql
2021-03-24 08:53:02.392563 (Thread-1): Parsing macros/materializations/snapshot/strategies.sql
2021-03-24 08:53:02.408998 (Thread-1): Parsing macros/materializations/snapshot/snapshot.sql
2021-03-24 08:53:02.437629 (Thread-1): Parsing macros/materializations/view/create_or_replace_view.sql
2021-03-24 08:53:02.442678 (Thread-1): Parsing macros/materializations/view/view.sql
2021-03-24 08:53:02.449625 (Thread-1): Parsing macros/materializations/seed/seed.sql
2021-03-24 08:53:02.470704 (Thread-1): Parsing macros/materializations/table/table.sql
2021-03-24 08:53:02.477990 (Thread-1): Parsing macros/materializations/incremental/helpers.sql
2021-03-24 08:53:02.482123 (Thread-1): Parsing macros/materializations/incremental/incremental.sql
2021-03-24 08:53:02.488081 (Thread-1): Parsing macros/etc/is_incremental.sql
2021-03-24 08:53:02.489725 (Thread-1): Parsing macros/etc/query.sql
2021-03-24 08:53:02.490815 (Thread-1): Parsing macros/etc/datetime.sql
2021-03-24 08:53:02.499956 (Thread-1): Parsing macros/etc/get_custom_alias.sql
2021-03-24 08:53:02.500944 (Thread-1): Parsing macros/etc/get_custom_database.sql
2021-03-24 08:53:02.502811 (Thread-1): Parsing macros/etc/get_custom_schema.sql
2021-03-24 08:53:02.504810 (Thread-1): Parsing macros/schema_tests/not_null.sql
2021-03-24 08:53:02.506513 (Thread-1): Parsing macros/schema_tests/accepted_values.sql
2021-03-24 08:53:02.509143 (Thread-1): Parsing macros/schema_tests/relationships.sql
2021-03-24 08:53:02.511016 (Thread-1): Parsing macros/schema_tests/unique.sql
2021-03-24 08:53:02.512707 (Thread-1): Parsing macros/adapters/common.sql
2021-03-24 08:53:02.560393 (Thread-1): * Deprecation Warning: dbt v0.17.0 introduces a new config format for the
dbt_project.yml file. Support for the existing version 1 format will be removed
in a future release of dbt. The following packages are currently configured with
config version 1:
 - demo_dbt

For upgrading instructions, consult the documentation:
  https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0

2021-03-24 08:53:02.560839 (Thread-1): Sending event: {'category': 'dbt', 'action': 'deprecation', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'property_': 'warn', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44bc137e50>]}
2021-03-24 08:53:02.861124 (Thread-1): [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_new_project.example

2021-03-24 08:53:03.068118 (Thread-2): handling status request
2021-03-24 08:53:03.068539 (Thread-2): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b46595b0>]}
2021-03-24 08:53:03.072594 (Thread-2): sending response (<Response 9608 bytes [200 OK]>) to 10.0.17.246
2021-03-24 09:05:43.449968 (Thread-3): handling status request
2021-03-24 09:05:43.451766 (Thread-3): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b46ba430>]}
2021-03-24 09:05:43.454937 (Thread-3): sending response (<Response 9608 bytes [200 OK]>) to 10.0.24.78
2021-03-24 09:05:44.448597 (Thread-4): handling compile_sql request
2021-03-24 09:05:44.449222 (Thread-4): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b465ffd0>]}
2021-03-24 09:05:45.807056 (Thread-4): sending response (<Response 138 bytes [200 OK]>) to 10.0.17.253
2021-03-24 09:05:45.833495 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 09:05:45.866308 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 09:05:45.867006 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 09:05:45.867159 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 09:05:45.893898 (Thread-1): finished collecting timing info
2021-03-24 09:05:45.894346 (Thread-1): finished collecting timing info
2021-03-24 09:05:46.455564 (Thread-5): handling poll request
2021-03-24 09:05:46.456066 (Thread-5): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b46459d0>]}
2021-03-24 09:05:46.463114 (Thread-5): sending response (<Response 5453 bytes [200 OK]>) to 10.0.7.139
2021-03-24 09:23:39.794118 (Thread-6): handling status request
2021-03-24 09:23:39.796516 (Thread-6): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b46483d0>]}
2021-03-24 09:23:39.803230 (Thread-6): sending response (<Response 9608 bytes [200 OK]>) to 10.0.7.139
2021-03-24 09:23:40.523207 (Thread-7): handling compile_sql request
2021-03-24 09:23:40.523650 (Thread-7): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b4648580>]}
2021-03-24 09:23:41.584406 (Thread-7): sending response (<Response 138 bytes [200 OK]>) to 10.0.33.168
2021-03-24 09:23:41.602458 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 09:23:41.619614 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 09:23:41.620093 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 09:23:41.620208 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 09:23:41.633777 (Thread-1): finished collecting timing info
2021-03-24 09:23:41.634025 (Thread-1): finished collecting timing info
2021-03-24 09:23:42.390728 (Thread-8): handling poll request
2021-03-24 09:23:42.391379 (Thread-8): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b475e7f0>]}
2021-03-24 09:23:42.398669 (Thread-8): sending response (<Response 4431 bytes [200 OK]>) to 10.0.45.139
2021-03-24 09:23:51.806544 (Thread-9): handling status request
2021-03-24 09:23:51.807263 (Thread-9): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b4779c70>]}
2021-03-24 09:23:51.814072 (Thread-9): sending response (<Response 9608 bytes [200 OK]>) to 10.0.28.180
2021-03-24 09:23:52.643665 (Thread-10): handling run_sql request
2021-03-24 09:23:52.645224 (Thread-10): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b4779850>]}
2021-03-24 09:23:53.784569 (Thread-10): sending response (<Response 138 bytes [200 OK]>) to 10.0.28.180
2021-03-24 09:23:53.801349 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 09:23:53.818312 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 09:23:53.818789 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 09:23:53.818902 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 09:23:53.832048 (Thread-1): finished collecting timing info
2021-03-24 09:23:53.832598 (Thread-1): Using snowflake connection "rpc.demo_dbt.request".
2021-03-24 09:23:53.832665 (Thread-1): On rpc.demo_dbt.request: select cust_id as id from ML_WORKSHOP.PUBLIC.CUSTOMER_CHURN where state='AK'
limit 500
/* limit added automatically by dbt cloud */
2021-03-24 09:23:53.832721 (Thread-1): Opening a new connection, currently in state init
2021-03-24 09:23:54.465959 (Thread-1): Snowflake query id: 019b1df3-0474-d406-0000-10b10113639e
2021-03-24 09:23:54.466110 (Thread-1): Snowflake error: 002003 (02000): SQL compilation error:
Database 'ML_WORKSHOP' does not exist or not authorized.
2021-03-24 09:23:54.466306 (Thread-1): finished collecting timing info
2021-03-24 09:23:54.466689 (Thread-1): On rpc.demo_dbt.request: Close
2021-03-24 09:23:54.517933 (Thread-1): Got an exception: Database Error
  002003 (02000): SQL compilation error:
  Database 'ML_WORKSHOP' does not exist or not authorized.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 161, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 78, in add_query
    cursor.execute(sql, bindings)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/cursor.py", line 595, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 68, in default_errorhandler
    raise errorclass(
snowflake.connector.errors.ProgrammingError: 002003 (02000): SQL compilation error:
Database 'ML_WORKSHOP' does not exist or not authorized.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 333, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 276, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 378, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 84, in execute
    _, execute_result = self.adapter.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 224, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 123, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 309, in add_query
    connection, cursor = super().add_query(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 86, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 178, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error
  002003 (02000): SQL compilation error:
  Database 'ML_WORKSHOP' does not exist or not authorized.
2021-03-24 09:23:54.519408 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': "Database Error in rpc request (from remote system)\n  002003 (02000): SQL compilation error:\n  Database 'ML_WORKSHOP' does not exist or not authorized.", 'raw_sql': "select cust_id as id from ML_WORKSHOP.PUBLIC.CUSTOMER_CHURN where state='AK'\nlimit 500\n/* limit added automatically by dbt cloud */", 'compiled_sql': "select cust_id as id from ML_WORKSHOP.PUBLIC.CUSTOMER_CHURN where state='AK'\nlimit 500\n/* limit added automatically by dbt cloud */", 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/rpc/sql_commands.py", line 145, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 349, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 52, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': "Database Error in rpc request (from remote system)\n  002003 (02000): SQL compilation error:\n  Database 'ML_WORKSHOP' does not exist or not authorized.", 'raw_sql': "select cust_id as id from ML_WORKSHOP.PUBLIC.CUSTOMER_CHURN where state='AK'\nlimit 500\n/* limit added automatically by dbt cloud */", 'compiled_sql': "select cust_id as id from ML_WORKSHOP.PUBLIC.CUSTOMER_CHURN where state='AK'\nlimit 500\n/* limit added automatically by dbt cloud */", 'tags': None}, None)
2021-03-24 09:23:54.590056 (Thread-11): handling poll request
2021-03-24 09:23:54.590569 (Thread-11): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b46ea4c0>]}
2021-03-24 09:23:54.594663 (Thread-11): sending response (<Response 9093 bytes [200 OK]>) to 10.0.35.128
2021-03-24 09:23:56.442680 (Thread-12): handling poll request
2021-03-24 09:23:56.443082 (Thread-12): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b477d040>]}
2021-03-24 09:23:56.443916 (Thread-12): sending response (<Response 9333 bytes [200 OK]>) to 10.0.7.139
2021-03-24 09:25:21.943332 (Thread-13): handling status request
2021-03-24 09:25:21.945439 (Thread-13): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b479f0d0>]}
2021-03-24 09:25:21.950851 (Thread-13): sending response (<Response 9608 bytes [200 OK]>) to 10.0.35.128
2021-03-24 09:25:22.585158 (Thread-14): handling compile_sql request
2021-03-24 09:25:22.585718 (Thread-14): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b479f0a0>]}
2021-03-24 09:25:23.709371 (Thread-14): sending response (<Response 138 bytes [200 OK]>) to 10.0.7.26
2021-03-24 09:25:23.727729 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 09:25:23.747331 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 09:25:23.747951 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 09:25:23.748094 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 09:25:23.761698 (Thread-1): finished collecting timing info
2021-03-24 09:25:23.761959 (Thread-1): finished collecting timing info
2021-03-24 09:25:24.472776 (Thread-15): handling poll request
2021-03-24 09:25:24.473431 (Thread-15): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b4665d60>]}
2021-03-24 09:25:24.479112 (Thread-15): sending response (<Response 4315 bytes [200 OK]>) to 10.0.9.204
2021-03-24 09:25:28.843244 (Thread-16): handling status request
2021-03-24 09:25:28.843684 (Thread-16): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b46656d0>]}
2021-03-24 09:25:28.846771 (Thread-16): sending response (<Response 9608 bytes [200 OK]>) to 10.0.24.78
2021-03-24 09:25:29.441618 (Thread-17): handling run_sql request
2021-03-24 09:25:29.442085 (Thread-17): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b466c520>]}
2021-03-24 09:25:30.457076 (Thread-17): sending response (<Response 138 bytes [200 OK]>) to 10.0.28.180
2021-03-24 09:25:30.480489 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 09:25:30.503193 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 09:25:30.503898 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 09:25:30.504165 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 09:25:30.533087 (Thread-1): finished collecting timing info
2021-03-24 09:25:30.533564 (Thread-1): Using snowflake connection "rpc.demo_dbt.request".
2021-03-24 09:25:30.533633 (Thread-1): On rpc.demo_dbt.request: select * from "RAMP"."GET_POC"."School_details"
limit 500
/* limit added automatically by dbt cloud */
2021-03-24 09:25:30.533689 (Thread-1): Opening a new connection, currently in state init
2021-03-24 09:25:31.189126 (Thread-18): handling poll request
2021-03-24 09:25:31.189787 (Thread-18): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b46267c0>]}
2021-03-24 09:25:31.192905 (Thread-18): sending response (<Response 2910 bytes [200 OK]>) to 10.0.26.226
2021-03-24 09:25:32.850126 (Thread-19): handling poll request
2021-03-24 09:25:32.850582 (Thread-19): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b4626d60>]}
2021-03-24 09:25:32.851589 (Thread-19): sending response (<Response 390 bytes [200 OK]>) to 10.0.9.29
2021-03-24 09:25:33.695197 (Thread-1): SQL status: SUCCESS 500 in 3.16 seconds
2021-03-24 09:25:34.835344 (Thread-20): handling poll request
2021-03-24 09:25:34.835801 (Thread-20): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b477d190>]}
2021-03-24 09:25:34.836736 (Thread-20): sending response (<Response 658 bytes [200 OK]>) to 10.0.35.128
2021-03-24 09:25:35.387171 (Thread-1): finished collecting timing info
2021-03-24 09:25:35.387626 (Thread-1): On rpc.demo_dbt.request: Close
2021-03-24 09:25:36.727189 (Thread-21): handling poll request
2021-03-24 09:25:36.727607 (Thread-21): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b4686cd0>]}
2021-03-24 09:25:36.801243 (Thread-21): sending response (<Response 2666932 bytes [200 OK]>) to 10.0.7.139
2021-03-24 11:14:49.641647 (Thread-22): handling status request
2021-03-24 11:14:49.643585 (Thread-22): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b4686d60>]}
2021-03-24 11:14:49.646668 (Thread-22): sending response (<Response 9608 bytes [200 OK]>) to 10.0.33.20
2021-03-24 11:14:50.246946 (Thread-23): handling compile_sql request
2021-03-24 11:14:50.247433 (Thread-23): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b4686ca0>]}
2021-03-24 11:14:51.298317 (Thread-23): sending response (<Response 138 bytes [200 OK]>) to 10.0.9.29
2021-03-24 11:14:51.315251 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 11:14:51.333960 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 11:14:51.334549 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 11:14:51.334660 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 11:14:51.348006 (Thread-1): finished collecting timing info
2021-03-24 11:14:51.348250 (Thread-1): finished collecting timing info
2021-03-24 11:14:52.161432 (Thread-24): handling poll request
2021-03-24 11:14:52.161887 (Thread-24): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b4686520>]}
2021-03-24 11:14:52.166373 (Thread-24): sending response (<Response 4631 bytes [200 OK]>) to 10.0.7.139
2021-03-24 11:15:57.220977 (Thread-25): handling status request
2021-03-24 11:15:57.221518 (Thread-25): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b479cca0>]}
2021-03-24 11:15:57.224626 (Thread-25): sending response (<Response 9608 bytes [200 OK]>) to 10.0.35.128
2021-03-24 11:15:58.214063 (Thread-26): handling run_sql request
2021-03-24 11:15:58.214574 (Thread-26): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b479cfa0>]}
2021-03-24 11:15:59.267807 (Thread-26): sending response (<Response 138 bytes [200 OK]>) to 10.0.33.20
2021-03-24 11:15:59.285417 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 11:15:59.304361 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 11:15:59.304842 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 11:15:59.304929 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 11:15:59.317940 (Thread-1): finished collecting timing info
2021-03-24 11:15:59.318408 (Thread-1): Using snowflake connection "rpc.demo_dbt.request".
2021-03-24 11:15:59.318472 (Thread-1): On rpc.demo_dbt.request: select * "RAMP"."GET_POC"."School_details" where "School Type" = 'HIGH SCHOOL' and "City" like '%Chicago%'
limit 500
/* limit added automatically by dbt cloud */
2021-03-24 11:15:59.318527 (Thread-1): Opening a new connection, currently in state init
2021-03-24 11:15:59.904468 (Thread-1): Snowflake query id: 019b1e63-0407-ece5-0000-10b1011365c2
2021-03-24 11:15:59.904658 (Thread-1): Snowflake error: 001003 (42000): SQL compilation error:
syntax error line 1 at position 9 unexpected '"RAMP"'.
2021-03-24 11:15:59.904844 (Thread-1): finished collecting timing info
2021-03-24 11:15:59.905338 (Thread-1): On rpc.demo_dbt.request: Close
2021-03-24 11:15:59.958418 (Thread-1): Got an exception: Database Error
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 9 unexpected '"RAMP"'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 161, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 78, in add_query
    cursor.execute(sql, bindings)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/cursor.py", line 595, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 68, in default_errorhandler
    raise errorclass(
snowflake.connector.errors.ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 1 at position 9 unexpected '"RAMP"'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 333, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 276, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 378, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 84, in execute
    _, execute_result = self.adapter.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 224, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 123, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 309, in add_query
    connection, cursor = super().add_query(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 86, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 178, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 9 unexpected '"RAMP"'.
2021-03-24 11:15:59.960474 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  001003 (42000): SQL compilation error:\n  syntax error line 1 at position 9 unexpected \'"RAMP"\'.', 'raw_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/rpc/sql_commands.py", line 145, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 349, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 52, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  001003 (42000): SQL compilation error:\n  syntax error line 1 at position 9 unexpected \'"RAMP"\'.', 'raw_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
2021-03-24 11:16:00.998051 (Thread-27): handling poll request
2021-03-24 11:16:00.998620 (Thread-27): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b479cac0>]}
2021-03-24 11:16:01.000040 (Thread-27): sending response (<Response 9641 bytes [200 OK]>) to 10.0.33.20
2021-03-24 11:16:23.653338 (Thread-28): handling status request
2021-03-24 11:16:23.653760 (Thread-28): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b47bfa90>]}
2021-03-24 11:16:23.656933 (Thread-28): sending response (<Response 9608 bytes [200 OK]>) to 10.0.45.139
2021-03-24 11:16:24.355203 (Thread-29): handling run_sql request
2021-03-24 11:16:24.355614 (Thread-29): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b47bfaf0>]}
2021-03-24 11:16:25.641113 (Thread-29): sending response (<Response 138 bytes [200 OK]>) to 10.0.33.20
2021-03-24 11:16:25.657881 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 11:16:25.673834 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 11:16:25.674399 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 11:16:25.674500 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 11:16:25.688287 (Thread-1): finished collecting timing info
2021-03-24 11:16:25.688730 (Thread-1): Using snowflake connection "rpc.demo_dbt.request".
2021-03-24 11:16:25.688795 (Thread-1): On rpc.demo_dbt.request: select * "RAMP"."GET_POC"."School_details" where "School Type" = 'HIGH SCHOOL' and "City" like '%Chicago%'
limit 500
/* limit added automatically by dbt cloud */
2021-03-24 11:16:25.688855 (Thread-1): Opening a new connection, currently in state init
2021-03-24 11:16:26.249035 (Thread-30): handling poll request
2021-03-24 11:16:26.249469 (Thread-30): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b45e27c0>]}
2021-03-24 11:16:26.251480 (Thread-30): sending response (<Response 2973 bytes [200 OK]>) to 10.0.9.29
2021-03-24 11:16:26.265926 (Thread-1): Snowflake query id: 019b1e64-046b-8130-0000-10b101134cb2
2021-03-24 11:16:26.266063 (Thread-1): Snowflake error: 001003 (42000): SQL compilation error:
syntax error line 1 at position 9 unexpected '"RAMP"'.
2021-03-24 11:16:26.266185 (Thread-1): finished collecting timing info
2021-03-24 11:16:26.266566 (Thread-1): On rpc.demo_dbt.request: Close
2021-03-24 11:16:26.314122 (Thread-1): Got an exception: Database Error
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 9 unexpected '"RAMP"'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 161, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 78, in add_query
    cursor.execute(sql, bindings)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/cursor.py", line 595, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 68, in default_errorhandler
    raise errorclass(
snowflake.connector.errors.ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 1 at position 9 unexpected '"RAMP"'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 333, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 276, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 378, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 84, in execute
    _, execute_result = self.adapter.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 224, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 123, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 309, in add_query
    connection, cursor = super().add_query(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 86, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 178, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 9 unexpected '"RAMP"'.
2021-03-24 11:16:26.316277 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  001003 (42000): SQL compilation error:\n  syntax error line 1 at position 9 unexpected \'"RAMP"\'.', 'raw_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/rpc/sql_commands.py", line 145, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 349, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 52, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  001003 (42000): SQL compilation error:\n  syntax error line 1 at position 9 unexpected \'"RAMP"\'.', 'raw_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
2021-03-24 11:16:28.131082 (Thread-31): handling poll request
2021-03-24 11:16:28.132090 (Thread-31): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b5000b50>]}
2021-03-24 11:16:28.133355 (Thread-31): sending response (<Response 9641 bytes [200 OK]>) to 10.0.17.253
2021-03-24 11:16:46.058770 (Thread-32): handling status request
2021-03-24 11:16:46.059220 (Thread-32): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b466c370>]}
2021-03-24 11:16:46.063400 (Thread-32): sending response (<Response 9608 bytes [200 OK]>) to 10.0.37.247
2021-03-24 11:16:46.675445 (Thread-33): handling compile_sql request
2021-03-24 11:16:46.675899 (Thread-33): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b4fd9310>]}
2021-03-24 11:16:47.734446 (Thread-33): sending response (<Response 138 bytes [200 OK]>) to 10.0.28.180
2021-03-24 11:16:47.751071 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 11:16:47.766620 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 11:16:47.767066 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 11:16:47.767176 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 11:16:47.779797 (Thread-1): finished collecting timing info
2021-03-24 11:16:47.780035 (Thread-1): finished collecting timing info
2021-03-24 11:16:48.615148 (Thread-34): handling poll request
2021-03-24 11:16:48.615814 (Thread-34): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b500e8b0>]}
2021-03-24 11:16:48.625353 (Thread-34): sending response (<Response 4481 bytes [200 OK]>) to 10.0.24.78
2021-03-24 11:16:50.649995 (Thread-35): handling status request
2021-03-24 11:16:50.650443 (Thread-35): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b500e790>]}
2021-03-24 11:16:50.653659 (Thread-35): sending response (<Response 9608 bytes [200 OK]>) to 10.0.35.128
2021-03-24 11:16:51.415603 (Thread-36): handling run_sql request
2021-03-24 11:16:51.416053 (Thread-36): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b500e520>]}
2021-03-24 11:16:52.478678 (Thread-36): sending response (<Response 138 bytes [200 OK]>) to 10.0.7.26
2021-03-24 11:16:52.495640 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 11:16:52.511842 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 11:16:52.512356 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 11:16:52.512464 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 11:16:52.525704 (Thread-1): finished collecting timing info
2021-03-24 11:16:52.526143 (Thread-1): Using snowflake connection "rpc.demo_dbt.request".
2021-03-24 11:16:52.526205 (Thread-1): On rpc.demo_dbt.request: select * "RAMP"."GET_POC"."School_details" where "School Type" = 'HIGH SCHOOL'
limit 500
/* limit added automatically by dbt cloud */
2021-03-24 11:16:52.526289 (Thread-1): Opening a new connection, currently in state init
2021-03-24 11:16:53.090787 (Thread-1): Snowflake query id: 019b1e64-044b-594d-0000-10b101134cb6
2021-03-24 11:16:53.090922 (Thread-1): Snowflake error: 001003 (42000): SQL compilation error:
syntax error line 1 at position 9 unexpected '"RAMP"'.
2021-03-24 11:16:53.091046 (Thread-1): finished collecting timing info
2021-03-24 11:16:53.091422 (Thread-1): On rpc.demo_dbt.request: Close
2021-03-24 11:16:53.139799 (Thread-1): Got an exception: Database Error
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 9 unexpected '"RAMP"'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 161, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 78, in add_query
    cursor.execute(sql, bindings)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/cursor.py", line 595, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 68, in default_errorhandler
    raise errorclass(
snowflake.connector.errors.ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 1 at position 9 unexpected '"RAMP"'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 333, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 276, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 378, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 84, in execute
    _, execute_result = self.adapter.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 224, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 123, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 309, in add_query
    connection, cursor = super().add_query(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 86, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 178, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 9 unexpected '"RAMP"'.
2021-03-24 11:16:53.141299 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  001003 (42000): SQL compilation error:\n  syntax error line 1 at position 9 unexpected \'"RAMP"\'.', 'raw_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/rpc/sql_commands.py", line 145, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 349, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 52, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  001003 (42000): SQL compilation error:\n  syntax error line 1 at position 9 unexpected \'"RAMP"\'.', 'raw_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
2021-03-24 11:16:53.193317 (Thread-37): handling poll request
2021-03-24 11:16:53.193959 (Thread-37): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b46b6970>]}
2021-03-24 11:16:53.197817 (Thread-37): sending response (<Response 9155 bytes [200 OK]>) to 10.0.45.139
2021-03-24 11:16:55.094046 (Thread-38): handling poll request
2021-03-24 11:16:55.094542 (Thread-38): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44b500e9d0>]}
2021-03-24 11:16:55.095791 (Thread-38): sending response (<Response 9415 bytes [200 OK]>) to 10.0.9.204
2021-03-24 11:17:01.330321 (Thread-39): Got an acceptable cached parse result
2021-03-24 11:17:01.485306 (Thread-39): [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_new_project.example

2021-03-24 11:17:01.942357 (Thread-40): handling status request
2021-03-24 11:17:01.942991 (Thread-40): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44af6c00d0>]}
2021-03-24 11:17:01.944431 (Thread-40): sending response (<Response 877 bytes [200 OK]>) to 10.0.41.120
2021-03-24 11:17:13.090834 (Thread-41): Got an acceptable cached parse result
2021-03-24 11:17:13.239631 (Thread-41): [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_new_project.example

2021-03-24 11:17:13.694617 (Thread-42): handling status request
2021-03-24 11:17:13.695193 (Thread-42): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'e10dbe0f-55e1-49c7-a6da-6ada3cd9174f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44af665ca0>]}
2021-03-24 11:17:13.696467 (Thread-42): sending response (<Response 877 bytes [200 OK]>) to 10.0.33.20
2021-03-24 15:56:34.414926 (MainThread): Running with dbt=0.18.1
2021-03-24 15:56:34.677002 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.rpc.server.RPCServerTask'>, debug=False, defer=None, exclude=None, host='0.0.0.0', log_cache_events=False, log_format='default', models=None, partial_parse=True, port=8580, profile='user', profiles_dir='/usr/src/develop/.dbt', project_dir=None, record_timing_info=None, rpc_method=None, single_threaded=False, state=None, strict=False, target=None, test_new_parser=False, threads=None, use_cache=True, use_colors=None, vars='{}', version_check=True, warn_error=False, which='rpc', write_json=True)
2021-03-24 15:56:34.689564 (MainThread): Tracking: tracking
2021-03-24 15:56:34.689790 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcae7f0a190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcae4f1f5e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad9e48c40>]}
2021-03-24 15:56:34.696441 (MainThread): Serving RPC server at 0.0.0.0:8580, pid=16
2021-03-24 15:56:34.701441 (MainThread): Supported methods: ['cli_args', 'compile', 'compile_sql', 'deps', 'docs.generate', 'gc', 'get-manifest', 'kill', 'poll', 'ps', 'run', 'run-operation', 'run_sql', 'seed', 'snapshot', 'snapshot-freshness', 'status', 'test']
2021-03-24 15:56:34.701855 (MainThread): Send requests to http://localhost:8580/jsonrpc
2021-03-24 15:56:34.709961 (Thread-1): Parsing macros/adapters.sql
2021-03-24 15:56:34.740090 (Thread-1): Parsing macros/catalog.sql
2021-03-24 15:56:34.742142 (Thread-1): Parsing macros/materializations/table.sql
2021-03-24 15:56:34.746036 (Thread-1): Parsing macros/materializations/merge.sql
2021-03-24 15:56:34.748028 (Thread-1): Parsing macros/materializations/incremental.sql
2021-03-24 15:56:34.757040 (Thread-1): Parsing macros/materializations/view.sql
2021-03-24 15:56:34.759290 (Thread-1): Parsing macros/core.sql
2021-03-24 15:56:34.762910 (Thread-1): Parsing macros/materializations/helpers.sql
2021-03-24 15:56:34.771861 (Thread-1): Parsing macros/materializations/common/merge.sql
2021-03-24 15:56:34.785922 (Thread-1): Parsing macros/materializations/snapshot/snapshot_merge.sql
2021-03-24 15:56:34.787750 (Thread-1): Parsing macros/materializations/snapshot/strategies.sql
2021-03-24 15:56:34.804176 (Thread-1): Parsing macros/materializations/snapshot/snapshot.sql
2021-03-24 15:56:34.833452 (Thread-2): handling status request
2021-03-24 15:56:34.834285 (Thread-2): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad9615160>]}
2021-03-24 15:56:34.835990 (Thread-2): sending response (<Response 185 bytes [200 OK]>) to 10.0.44.18
2021-03-24 15:56:34.836837 (Thread-1): Parsing macros/materializations/view/create_or_replace_view.sql
2021-03-24 15:56:34.842127 (Thread-1): Parsing macros/materializations/view/view.sql
2021-03-24 15:56:34.849640 (Thread-1): Parsing macros/materializations/seed/seed.sql
2021-03-24 15:56:34.870675 (Thread-1): Parsing macros/materializations/table/table.sql
2021-03-24 15:56:34.877341 (Thread-1): Parsing macros/materializations/incremental/helpers.sql
2021-03-24 15:56:34.879232 (Thread-1): Parsing macros/materializations/incremental/incremental.sql
2021-03-24 15:56:34.885227 (Thread-1): Parsing macros/etc/is_incremental.sql
2021-03-24 15:56:34.886886 (Thread-1): Parsing macros/etc/query.sql
2021-03-24 15:56:34.887979 (Thread-1): Parsing macros/etc/datetime.sql
2021-03-24 15:56:34.897870 (Thread-1): Parsing macros/etc/get_custom_alias.sql
2021-03-24 15:56:34.898861 (Thread-1): Parsing macros/etc/get_custom_database.sql
2021-03-24 15:56:34.900545 (Thread-1): Parsing macros/etc/get_custom_schema.sql
2021-03-24 15:56:34.902496 (Thread-1): Parsing macros/schema_tests/not_null.sql
2021-03-24 15:56:34.904053 (Thread-1): Parsing macros/schema_tests/accepted_values.sql
2021-03-24 15:56:34.906687 (Thread-1): Parsing macros/schema_tests/relationships.sql
2021-03-24 15:56:34.908574 (Thread-1): Parsing macros/schema_tests/unique.sql
2021-03-24 15:56:34.910345 (Thread-1): Parsing macros/adapters/common.sql
2021-03-24 15:56:34.958543 (Thread-1): * Deprecation Warning: dbt v0.17.0 introduces a new config format for the
dbt_project.yml file. Support for the existing version 1 format will be removed
in a future release of dbt. The following packages are currently configured with
config version 1:
 - demo_dbt

For upgrading instructions, consult the documentation:
  https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0

2021-03-24 15:56:34.958925 (Thread-1): Sending event: {'category': 'dbt', 'action': 'deprecation', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'property_': 'warn', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad9e48bb0>]}
2021-03-24 15:56:35.240156 (Thread-1): [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_new_project.example

2021-03-24 15:56:36.526296 (Thread-3): handling status request
2021-03-24 15:56:36.526737 (Thread-3): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8d861c0>]}
2021-03-24 15:56:36.529947 (Thread-3): sending response (<Response 9608 bytes [200 OK]>) to 10.0.26.20
2021-03-24 15:56:50.456308 (Thread-4): handling status request
2021-03-24 15:56:50.458330 (Thread-4): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8c9be50>]}
2021-03-24 15:56:50.461651 (Thread-4): sending response (<Response 9608 bytes [200 OK]>) to 10.0.35.60
2021-03-24 15:56:51.129418 (Thread-5): handling run_sql request
2021-03-24 15:56:51.129837 (Thread-5): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8c9b0a0>]}
2021-03-24 15:56:52.242003 (Thread-5): sending response (<Response 138 bytes [200 OK]>) to 10.0.44.18
2021-03-24 15:56:52.258233 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 15:56:52.274882 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 15:56:52.275430 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 15:56:52.275542 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 15:56:52.291530 (Thread-1): finished collecting timing info
2021-03-24 15:56:52.292059 (Thread-1): Using snowflake connection "rpc.demo_dbt.request".
2021-03-24 15:56:52.292142 (Thread-1): On rpc.demo_dbt.request: select * "RAMP"."GET_POC"."School_details" where "School Type" = 'HIGH SCHOOL' and "City" like '%Chicago%'
limit 500
/* limit added automatically by dbt cloud */
2021-03-24 15:56:52.292208 (Thread-1): Opening a new connection, currently in state init
2021-03-24 15:56:53.053090 (Thread-1): Snowflake query id: 019b1f7c-04dc-e1f3-0000-10b101134e76
2021-03-24 15:56:53.053235 (Thread-1): Snowflake error: 001003 (42000): SQL compilation error:
syntax error line 1 at position 9 unexpected '"RAMP"'.
2021-03-24 15:56:53.053365 (Thread-1): finished collecting timing info
2021-03-24 15:56:53.053744 (Thread-1): On rpc.demo_dbt.request: Close
2021-03-24 15:56:53.193620 (Thread-6): handling poll request
2021-03-24 15:56:53.194083 (Thread-6): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad9e80e20>]}
2021-03-24 15:56:53.197789 (Thread-6): sending response (<Response 4266 bytes [200 OK]>) to 10.0.13.135
2021-03-24 15:56:53.201633 (Thread-1): Got an exception: Database Error
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 9 unexpected '"RAMP"'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 161, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 78, in add_query
    cursor.execute(sql, bindings)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/cursor.py", line 595, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 68, in default_errorhandler
    raise errorclass(
snowflake.connector.errors.ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 1 at position 9 unexpected '"RAMP"'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 333, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 276, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 378, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 84, in execute
    _, execute_result = self.adapter.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 224, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 123, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 309, in add_query
    connection, cursor = super().add_query(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 86, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 178, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 9 unexpected '"RAMP"'.
2021-03-24 15:56:53.203926 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  001003 (42000): SQL compilation error:\n  syntax error line 1 at position 9 unexpected \'"RAMP"\'.', 'raw_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/rpc/sql_commands.py", line 145, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 349, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 52, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  001003 (42000): SQL compilation error:\n  syntax error line 1 at position 9 unexpected \'"RAMP"\'.', 'raw_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
2021-03-24 15:56:54.841806 (Thread-7): handling poll request
2021-03-24 15:56:54.842245 (Thread-7): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad9e91880>]}
2021-03-24 15:56:54.843131 (Thread-7): sending response (<Response 9627 bytes [200 OK]>) to 10.0.26.20
2021-03-24 15:57:07.238997 (Thread-8): handling status request
2021-03-24 15:57:07.239435 (Thread-8): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad9e91d30>]}
2021-03-24 15:57:07.242712 (Thread-8): sending response (<Response 9608 bytes [200 OK]>) to 10.0.35.60
2021-03-24 15:57:07.942169 (Thread-9): handling run_sql request
2021-03-24 15:57:07.944261 (Thread-9): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad9e960a0>]}
2021-03-24 15:57:09.010566 (Thread-9): sending response (<Response 138 bytes [200 OK]>) to 10.0.42.11
2021-03-24 15:57:09.027909 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 15:57:09.044728 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 15:57:09.045259 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 15:57:09.045376 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 15:57:09.060814 (Thread-1): finished collecting timing info
2021-03-24 15:57:09.061325 (Thread-1): Using snowflake connection "rpc.demo_dbt.request".
2021-03-24 15:57:09.061398 (Thread-1): On rpc.demo_dbt.request: select * from  "RAMP"."GET_POC"."School_details" where "School Type" = 'HIGH SCHOOL' and "City" like '%Chicago%'
limit 500
/* limit added automatically by dbt cloud */
2021-03-24 15:57:09.061456 (Thread-1): Opening a new connection, currently in state init
2021-03-24 15:57:09.614810 (Thread-10): handling poll request
2021-03-24 15:57:09.615271 (Thread-10): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8d41040>]}
2021-03-24 15:57:09.617541 (Thread-10): sending response (<Response 2979 bytes [200 OK]>) to 10.0.26.20
2021-03-24 15:57:11.358690 (Thread-11): handling poll request
2021-03-24 15:57:11.359114 (Thread-11): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8d41970>]}
2021-03-24 15:57:11.360169 (Thread-11): sending response (<Response 389 bytes [200 OK]>) to 10.0.33.70
2021-03-24 15:57:13.079972 (Thread-12): handling poll request
2021-03-24 15:57:13.080435 (Thread-12): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8c9c9d0>]}
2021-03-24 15:57:13.081535 (Thread-12): sending response (<Response 390 bytes [200 OK]>) to 10.0.28.153
2021-03-24 15:57:13.404578 (Thread-1): SQL status: SUCCESS 93 in 4.34 seconds
2021-03-24 15:57:13.922399 (Thread-1): finished collecting timing info
2021-03-24 15:57:13.922859 (Thread-1): On rpc.demo_dbt.request: Close
2021-03-24 15:57:14.983474 (Thread-13): handling poll request
2021-03-24 15:57:14.984021 (Thread-13): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8ca86d0>]}
2021-03-24 15:57:15.008970 (Thread-13): sending response (<Response 544616 bytes [200 OK]>) to 10.0.13.135
2021-03-24 16:00:11.927373 (Thread-14): handling status request
2021-03-24 16:00:11.929641 (Thread-14): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8ca8160>]}
2021-03-24 16:00:11.933327 (Thread-14): sending response (<Response 9608 bytes [200 OK]>) to 10.0.35.60
2021-03-24 16:00:12.767423 (Thread-15): handling run_sql request
2021-03-24 16:00:12.767845 (Thread-15): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8ca8820>]}
2021-03-24 16:00:13.798685 (Thread-15): sending response (<Response 138 bytes [200 OK]>) to 10.0.26.20
2021-03-24 16:00:13.815356 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:00:13.834704 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 16:00:13.835185 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:00:13.835296 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 16:00:13.848798 (Thread-1): finished collecting timing info
2021-03-24 16:00:13.849296 (Thread-1): Using snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:00:13.849361 (Thread-1): On rpc.demo_dbt.request: select RCDTS, "SCHOOL NAME", District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = 'HIGH SCHOOL' and "City" like '%Chicago%'
limit 500
/* limit added automatically by dbt cloud */
2021-03-24 16:00:13.849420 (Thread-1): Opening a new connection, currently in state init
2021-03-24 16:00:14.434471 (Thread-16): handling poll request
2021-03-24 16:00:14.434928 (Thread-16): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8c9b220>]}
2021-03-24 16:00:14.437214 (Thread-16): sending response (<Response 3022 bytes [200 OK]>) to 10.0.26.20
2021-03-24 16:00:14.826829 (Thread-1): Snowflake query id: 019b1f80-048f-18a9-0000-10b1011367ae
2021-03-24 16:00:14.826972 (Thread-1): Snowflake error: 000904 (42000): SQL compilation error: error line 1 at position 14
invalid identifier '"SCHOOL NAME"'
2021-03-24 16:00:14.827102 (Thread-1): finished collecting timing info
2021-03-24 16:00:14.827486 (Thread-1): On rpc.demo_dbt.request: Close
2021-03-24 16:00:14.925885 (Thread-1): Got an exception: Database Error
  000904 (42000): SQL compilation error: error line 1 at position 14
  invalid identifier '"SCHOOL NAME"'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 161, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 78, in add_query
    cursor.execute(sql, bindings)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/cursor.py", line 595, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 68, in default_errorhandler
    raise errorclass(
snowflake.connector.errors.ProgrammingError: 000904 (42000): SQL compilation error: error line 1 at position 14
invalid identifier '"SCHOOL NAME"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 333, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 276, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 378, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 84, in execute
    _, execute_result = self.adapter.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 224, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 123, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 309, in add_query
    connection, cursor = super().add_query(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 86, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 178, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error
  000904 (42000): SQL compilation error: error line 1 at position 14
  invalid identifier '"SCHOOL NAME"'
2021-03-24 16:00:14.927256 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  000904 (42000): SQL compilation error: error line 1 at position 14\n  invalid identifier \'"SCHOOL NAME"\'', 'raw_sql': 'select RCDTS, "SCHOOL NAME", District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select RCDTS, "SCHOOL NAME", District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/rpc/sql_commands.py", line 145, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 349, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 52, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  000904 (42000): SQL compilation error: error line 1 at position 14\n  invalid identifier \'"SCHOOL NAME"\'', 'raw_sql': 'select RCDTS, "SCHOOL NAME", District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select RCDTS, "SCHOOL NAME", District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
2021-03-24 16:00:16.072679 (Thread-17): handling poll request
2021-03-24 16:00:16.073109 (Thread-17): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad95ad9d0>]}
2021-03-24 16:00:16.073986 (Thread-17): sending response (<Response 10040 bytes [200 OK]>) to 10.0.6.15
2021-03-24 16:00:37.672118 (Thread-18): handling status request
2021-03-24 16:00:37.672557 (Thread-18): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8c9ba30>]}
2021-03-24 16:00:37.675720 (Thread-18): sending response (<Response 9608 bytes [200 OK]>) to 10.0.26.135
2021-03-24 16:00:38.350826 (Thread-19): handling run_sql request
2021-03-24 16:00:38.351253 (Thread-19): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8c9bd00>]}
2021-03-24 16:00:39.483919 (Thread-19): sending response (<Response 138 bytes [200 OK]>) to 10.0.21.253
2021-03-24 16:00:39.500322 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:00:39.518084 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 16:00:39.518753 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:00:39.518878 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 16:00:39.533325 (Thread-1): finished collecting timing info
2021-03-24 16:00:39.533896 (Thread-1): Using snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:00:39.533978 (Thread-1): On rpc.demo_dbt.request: select RCDTS, 'SCHOOL NAME', District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = 'HIGH SCHOOL' and "City" like '%Chicago%'
limit 500
/* limit added automatically by dbt cloud */
2021-03-24 16:00:39.534045 (Thread-1): Opening a new connection, currently in state init
2021-03-24 16:00:40.255008 (Thread-20): handling poll request
2021-03-24 16:00:40.255594 (Thread-20): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8d5c970>]}
2021-03-24 16:00:40.254149 (Thread-1): Snowflake query id: 019b1f80-04a3-c216-0000-10b1011367b2
2021-03-24 16:00:40.258194 (Thread-20): sending response (<Response 3308 bytes [200 OK]>) to 10.0.32.108
2021-03-24 16:00:40.254291 (Thread-1): Snowflake error: 000904 (42000): SQL compilation error: error line 1 at position 29
invalid identifier 'DISTRICT'
2021-03-24 16:00:40.254426 (Thread-1): finished collecting timing info
2021-03-24 16:00:40.255042 (Thread-1): On rpc.demo_dbt.request: Close
2021-03-24 16:00:40.334263 (Thread-1): Got an exception: Database Error
  000904 (42000): SQL compilation error: error line 1 at position 29
  invalid identifier 'DISTRICT'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 161, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 78, in add_query
    cursor.execute(sql, bindings)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/cursor.py", line 595, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 68, in default_errorhandler
    raise errorclass(
snowflake.connector.errors.ProgrammingError: 000904 (42000): SQL compilation error: error line 1 at position 29
invalid identifier 'DISTRICT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 333, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 276, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 378, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 84, in execute
    _, execute_result = self.adapter.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 224, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 123, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 309, in add_query
    connection, cursor = super().add_query(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 86, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 178, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error
  000904 (42000): SQL compilation error: error line 1 at position 29
  invalid identifier 'DISTRICT'
2021-03-24 16:00:40.336659 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': "Database Error in rpc request (from remote system)\n  000904 (42000): SQL compilation error: error line 1 at position 29\n  invalid identifier 'DISTRICT'", 'raw_sql': 'select RCDTS, \'SCHOOL NAME\', District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select RCDTS, \'SCHOOL NAME\', District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/rpc/sql_commands.py", line 145, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 349, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 52, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': "Database Error in rpc request (from remote system)\n  000904 (42000): SQL compilation error: error line 1 at position 29\n  invalid identifier 'DISTRICT'", 'raw_sql': 'select RCDTS, \'SCHOOL NAME\', District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select RCDTS, \'SCHOOL NAME\', District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
2021-03-24 16:00:42.042789 (Thread-21): handling poll request
2021-03-24 16:00:42.043230 (Thread-21): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8cb7250>]}
2021-03-24 16:00:42.044161 (Thread-21): sending response (<Response 9989 bytes [200 OK]>) to 10.0.13.135
2021-03-24 16:00:57.734820 (Thread-22): handling status request
2021-03-24 16:00:57.735553 (Thread-22): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8d5ccd0>]}
2021-03-24 16:00:57.738925 (Thread-22): sending response (<Response 9608 bytes [200 OK]>) to 10.0.33.70
2021-03-24 16:00:58.510669 (Thread-23): handling run_sql request
2021-03-24 16:00:58.511118 (Thread-23): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8d5c4c0>]}
2021-03-24 16:00:59.758334 (Thread-23): sending response (<Response 138 bytes [200 OK]>) to 10.0.28.153
2021-03-24 16:00:59.777993 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:00:59.800069 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 16:00:59.800592 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:00:59.800700 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 16:00:59.816621 (Thread-1): finished collecting timing info
2021-03-24 16:00:59.817281 (Thread-1): Using snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:00:59.817365 (Thread-1): On rpc.demo_dbt.request: select RCDTS, District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = 'HIGH SCHOOL' and "City" like '%Chicago%'
limit 500
/* limit added automatically by dbt cloud */
2021-03-24 16:00:59.817435 (Thread-1): Opening a new connection, currently in state init
2021-03-24 16:01:00.387596 (Thread-24): handling poll request
2021-03-24 16:01:00.388108 (Thread-24): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8d867c0>]}
2021-03-24 16:01:00.390173 (Thread-24): sending response (<Response 3005 bytes [200 OK]>) to 10.0.28.153
2021-03-24 16:01:01.628692 (Thread-1): Snowflake query id: 019b1f81-0419-cb97-0000-10b101134e7e
2021-03-24 16:01:01.628887 (Thread-1): Snowflake error: 000904 (42000): SQL compilation error: error line 1 at position 14
invalid identifier 'DISTRICT'
2021-03-24 16:01:01.629072 (Thread-1): finished collecting timing info
2021-03-24 16:01:01.629613 (Thread-1): On rpc.demo_dbt.request: Close
2021-03-24 16:01:02.232896 (Thread-1): Got an exception: Database Error
  000904 (42000): SQL compilation error: error line 1 at position 14
  invalid identifier 'DISTRICT'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 161, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 78, in add_query
    cursor.execute(sql, bindings)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/cursor.py", line 595, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 68, in default_errorhandler
    raise errorclass(
snowflake.connector.errors.ProgrammingError: 000904 (42000): SQL compilation error: error line 1 at position 14
invalid identifier 'DISTRICT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 333, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 276, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 378, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 84, in execute
    _, execute_result = self.adapter.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 224, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 123, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 309, in add_query
    connection, cursor = super().add_query(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 86, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 178, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error
  000904 (42000): SQL compilation error: error line 1 at position 14
  invalid identifier 'DISTRICT'
2021-03-24 16:01:02.235391 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': "Database Error in rpc request (from remote system)\n  000904 (42000): SQL compilation error: error line 1 at position 14\n  invalid identifier 'DISTRICT'", 'raw_sql': 'select RCDTS, District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select RCDTS, District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/rpc/sql_commands.py", line 145, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 349, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 52, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': "Database Error in rpc request (from remote system)\n  000904 (42000): SQL compilation error: error line 1 at position 14\n  invalid identifier 'DISTRICT'", 'raw_sql': 'select RCDTS, District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select RCDTS, District,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
2021-03-24 16:01:02.356570 (Thread-25): handling poll request
2021-03-24 16:01:02.357165 (Thread-25): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8d86ac0>]}
2021-03-24 16:01:02.359295 (Thread-25): sending response (<Response 6866 bytes [200 OK]>) to 10.0.13.135
2021-03-24 16:01:04.053286 (Thread-26): handling poll request
2021-03-24 16:01:04.053840 (Thread-26): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8d86b50>]}
2021-03-24 16:01:04.054949 (Thread-26): sending response (<Response 9868 bytes [200 OK]>) to 10.0.13.135
2021-03-24 16:01:17.756150 (Thread-27): handling status request
2021-03-24 16:01:17.756747 (Thread-27): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8d86790>]}
2021-03-24 16:01:17.762259 (Thread-27): sending response (<Response 9608 bytes [200 OK]>) to 10.0.35.60
2021-03-24 16:01:19.269024 (Thread-28): handling run_sql request
2021-03-24 16:01:19.269704 (Thread-28): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8d5c7c0>]}
2021-03-24 16:01:20.869808 (Thread-28): sending response (<Response 138 bytes [200 OK]>) to 10.0.30.8
2021-03-24 16:01:20.902413 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:01:20.934219 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 16:01:20.934776 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:01:20.934933 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 16:01:20.958474 (Thread-1): finished collecting timing info
2021-03-24 16:01:20.959259 (Thread-1): Using snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:01:20.959387 (Thread-1): On rpc.demo_dbt.request: select RCDTS,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = 'HIGH SCHOOL' and "City" like '%Chicago%'
limit 500
/* limit added automatically by dbt cloud */
2021-03-24 16:01:20.959503 (Thread-1): Opening a new connection, currently in state init
2021-03-24 16:01:21.745277 (Thread-29): handling poll request
2021-03-24 16:01:21.745913 (Thread-29): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8c12b20>]}
2021-03-24 16:01:22.083837 (Thread-29): sending response (<Response 2994 bytes [200 OK]>) to 10.0.3.63
2021-03-24 16:01:22.428806 (Thread-1): Snowflake query id: 019b1f81-04f1-2461-0000-10b1011367b6
2021-03-24 16:01:22.428987 (Thread-1): Snowflake error: 000904 (42000): SQL compilation error: error line 1 at position 13
invalid identifier 'CITY'
2021-03-24 16:01:22.429164 (Thread-1): finished collecting timing info
2021-03-24 16:01:22.429689 (Thread-1): On rpc.demo_dbt.request: Close
2021-03-24 16:01:22.491766 (Thread-1): Got an exception: Database Error
  000904 (42000): SQL compilation error: error line 1 at position 13
  invalid identifier 'CITY'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 161, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 78, in add_query
    cursor.execute(sql, bindings)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/cursor.py", line 595, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python3.8/dist-packages/snowflake/connector/errors.py", line 68, in default_errorhandler
    raise errorclass(
snowflake.connector.errors.ProgrammingError: 000904 (42000): SQL compilation error: error line 1 at position 13
invalid identifier 'CITY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 333, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 276, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 378, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 84, in execute
    _, execute_result = self.adapter.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 224, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 123, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 309, in add_query
    connection, cursor = super().add_query(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 86, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/snowflake/connections.py", line 178, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error
  000904 (42000): SQL compilation error: error line 1 at position 13
  invalid identifier 'CITY'
2021-03-24 16:01:22.496259 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': "Database Error in rpc request (from remote system)\n  000904 (42000): SQL compilation error: error line 1 at position 13\n  invalid identifier 'CITY'", 'raw_sql': 'select RCDTS,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select RCDTS,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/rpc/sql_commands.py", line 145, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 349, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 52, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': "Database Error in rpc request (from remote system)\n  000904 (42000): SQL compilation error: error line 1 at position 13\n  invalid identifier 'CITY'", 'raw_sql': 'select RCDTS,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select RCDTS,City,County From  "RAMP"."GET_POC"."School_details" where "School Type" = \'HIGH SCHOOL\' and "City" like \'%Chicago%\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
2021-03-24 16:01:24.227850 (Thread-30): handling poll request
2021-03-24 16:01:24.228520 (Thread-30): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8c2f910>]}
2021-03-24 16:01:24.229795 (Thread-30): sending response (<Response 9770 bytes [200 OK]>) to 10.0.13.135
2021-03-24 16:01:42.523245 (Thread-31): handling status request
2021-03-24 16:01:42.523855 (Thread-31): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8d08100>]}
2021-03-24 16:01:42.529739 (Thread-31): sending response (<Response 9608 bytes [200 OK]>) to 10.0.21.253
2021-03-24 16:01:43.312785 (Thread-32): handling run_sql request
2021-03-24 16:01:43.313453 (Thread-32): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8c014f0>]}
2021-03-24 16:01:45.166938 (Thread-32): sending response (<Response 138 bytes [200 OK]>) to 10.0.44.18
2021-03-24 16:01:45.196223 (MainThread): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:01:45.220991 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 0 sources
2021-03-24 16:01:45.222403 (Thread-1): Acquiring new snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:01:45.222570 (Thread-1): Compiling rpc.demo_dbt.request
2021-03-24 16:01:45.253152 (Thread-1): finished collecting timing info
2021-03-24 16:01:45.253938 (Thread-1): Using snowflake connection "rpc.demo_dbt.request".
2021-03-24 16:01:45.254058 (Thread-1): On rpc.demo_dbt.request: select RCDTS From  "RAMP"."GET_POC"."School_details" where "School Type" = 'HIGH SCHOOL' and "City" like '%Chicago%'
limit 500
/* limit added automatically by dbt cloud */
2021-03-24 16:01:45.254145 (Thread-1): Opening a new connection, currently in state init
2021-03-24 16:01:46.463677 (Thread-33): handling poll request
2021-03-24 16:01:46.464473 (Thread-33): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8c7ec40>]}
2021-03-24 16:01:46.468450 (Thread-33): sending response (<Response 2983 bytes [200 OK]>) to 10.0.32.108
2021-03-24 16:01:46.801428 (Thread-1): SQL status: SUCCESS 93 in 1.55 seconds
2021-03-24 16:01:46.812087 (Thread-1): finished collecting timing info
2021-03-24 16:01:46.812674 (Thread-1): On rpc.demo_dbt.request: Close
2021-03-24 16:01:48.377140 (Thread-34): handling poll request
2021-03-24 16:01:48.377732 (Thread-34): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8cc6f10>]}
2021-03-24 16:01:48.382884 (Thread-34): sending response (<Response 5618 bytes [200 OK]>) to 10.0.33.70
2021-03-24 16:01:58.385183 (Thread-35): Got an acceptable cached parse result
2021-03-24 16:01:58.637016 (Thread-35): [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_new_project.example

2021-03-24 16:01:59.552365 (Thread-36): handling status request
2021-03-24 16:01:59.553004 (Thread-36): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad84f85e0>]}
2021-03-24 16:01:59.554402 (Thread-36): sending response (<Response 877 bytes [200 OK]>) to 10.0.30.8
2021-03-24 16:02:20.623322 (Thread-37): handling status request
2021-03-24 16:02:20.623976 (Thread-37): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': 'f6b776e9-1222-405f-b426-45769340336b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcad8bd7910>]}
2021-03-24 16:02:20.625246 (Thread-37): sending response (<Response 877 bytes [200 OK]>) to 10.0.26.20
